### ISSUE TITLE
Update homepage branding

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-android#35]
We need following images with Ghostery branding:

* [ic_wordmark_logo](https://github.com/ghostery/user-agent-android/assets/1228153/515a2f12-5db4-427a-87f8-0cba364680a3)
* [ic_wordmark_text_private](https://github.com/ghostery/user-agent-android/assets/1228153/b2174850-3d77-4c81-b88f-c6e746b7a72c)
* [ic_wordmark_text_normal](https://github.com/ghostery/user-agent-android/assets/1228153/9ef6ca54-7751-42c7-b1ad-8a85ac6b9121)

Should be based on previously used SVGs:
* [ic_logo_wordmark_normal](https://github.com/ghostery/user-agent-android/assets/1228153/57c76ce5-8dcb-4e21-a081-2e1c706f2ce1)
* [ic_logo_wordmark_private](https://github.com/ghostery/user-agent-android/assets/1228153/e820b8bb-8c07-453b-ae30-82f1723f7982)
* [ic_logo_wordmark_white](https://github.com/ghostery/user-agent-android/assets/1228153/1ec93c35-b0f1-4a02-a614-26958687faaf)

**Comment by kalinme** [comment]
[updated assets.zip](https://github.com/ghostery/user-agent-android/files/12212868/updated.assets.zip)

@chrmod please check these assets
