### ISSUE TITLE
New Google Play assets for release 2023.9

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-android#44]
2023.9 ships Ghostery 10 so we have to update all screenshots.

**Comment by kalinme** [comment]
@chrmod added new screenshots here: https://www.figma.com/file/wVfqhLNwlM1wFY1iRBgBsT/Ghostery-Browser?type=design&node-id=318%3A583&mode=design&t=ycqgzzRgo0Dozs7a-1

check if they all are good
